const currencies = [
  { value: 'BTC', label: 'BTC - Bitcoin' },
  { value: 'ETH', label: 'ETH - Ethereum' },
  { value: 'BNB', label: 'BNB - Binance Coin' },
  { value: 'USDT', label: 'USDT - Tether' },
  { value: 'ADA', label: 'ADA - Cardano' },
  { value: 'DOT', label: 'DOT - Polkadot' },
  { value: 'XRP', label: 'XRP - XRP' },
  { value: 'UNI', label: 'UNI - Uniswap' },
  { value: 'LTC', label: 'LTC - Litecoin' },
  { value: 'LINK', label: 'LINK - Chainlink' },
  { value: 'USDC', label: 'USDC - USD Coin' },
  { value: 'BCH', label: 'BCH - Bitcoin Cash' },
  { value: 'THETA', label: 'THETA - THETA' },
  { value: 'XLM', label: 'XLM - Stellar' },
  { value: 'LUNA', label: 'LUNA - Terra' },
  { value: 'WBTC', label: 'WBTC - Wrapped Bitcoin' },
  { value: 'DOGE', label: 'DOGE - Dogecoin' },
  { value: 'VET', label: 'VET - VeChain' },
  { value: 'CRO', label: 'CRO - Crypto.com Coin' },
  { value: 'FIL', label: 'FIL - Filecoin' },
  { value: 'AAVE', label: 'AAVE - Aave' },
  { value: 'TRX', label: 'TRX - TRON' },
  { value: 'ATOM', label: 'ATOM - Cosmos' },
  { value: 'AVAX', label: 'AVAX - Avalanche' },
  { value: 'XMR', label: 'XMR - Monero' },
  { value: 'EOS', label: 'EOS - EOS' },
  { value: 'MIOTA', label: 'MIOTA - IOTA' },
  { value: 'BSV', label: 'BSV - Bitcoin SV' },
  { value: 'SOL', label: 'SOL - Solana' },
  { value: 'FTT', label: 'FTT - FTX Token' },
  { value: 'BTT', label: 'BTT - BitTorrent' },
  { value: 'KSM', label: 'KSM - Kusama' },
  { value: 'XEM', label: 'XEM - NEM' },
  { value: 'XTZ', label: 'XTZ - Tezos' },
  { value: 'BUSD', label: 'BUSD - Binance USD' },
  { value: 'CHZ', label: 'CHZ - Chiliz' },
  { value: 'ALGO', label: 'ALGO - Algorand' },
  { value: 'NEO', label: 'NEO - Neo' },
  { value: 'DAI', label: 'DAI - Dai' },
  { value: 'HBAR', label: 'HBAR - Hedera Hashgraph' },
  { value: 'HT', label: 'HT - Huobi Token' },
  { value: 'SUSHI', label: 'SUSHI - SushiSwap' },
  { value: 'EGLD', label: 'EGLD - Elrond' },
  { value: 'SNX', label: 'SNX - Synthetix' },
  { value: 'DASH', label: 'DASH - Dash' },
  { value: 'LEO', label: 'LEO - UNUS SED LEO' },
  { value: 'GRT', label: 'GRT - The Graph' },
  { value: 'DCR', label: 'DCR - Decred' },
  { value: 'MKR', label: 'MKR - Maker' },
  { value: 'ENJ', label: 'ENJ - Enjin Coin' },
  { value: 'NEAR', label: 'NEAR - NEAR Protocol' },
  { value: 'MATIC', label: 'MATIC - Polygon' },
  { value: 'ZIL', label: 'ZIL - Zilliqa' },
  { value: 'COMP', label: 'COMP - Compound' },
  { value: 'RVN', label: 'RVN - Ravencoin' },
  { value: 'NPXS', label: 'NPXS - Pundi X' },
  { value: 'ZEC', label: 'ZEC - Zcash' },
  { value: 'TFUEL', label: 'TFUEL - Theta Fuel' },
  { value: 'BAT', label: 'BAT - Basic Attention Token' },
  { value: 'MANA', label: 'MANA - Decentraland' },
  { value: 'ONE', label: 'ONE - Harmony' },
  { value: 'NEXO', label: 'NEXO - Nexo' },
  { value: 'UMA', label: 'UMA - UMA' },
  { value: 'BTCB', label: 'BTCB - Bitcoin BEP2' },
  { value: 'ETC', label: 'ETC - Ethereum Classic' },
  { value: 'CAKE', label: 'CAKE - PancakeSwap' },
  { value: 'STX', label: 'STX - Stacks' },
  { value: 'HOT', label: 'HOT - Holo' },
  { value: 'BNT', label: 'BNT - Bancor' },
  { value: 'CHSB', label: 'CHSB - SwissBorg' },
  { value: 'RUNE', label: 'RUNE - THORChain' },
  { value: 'UST', label: 'UST - TerraUSD' },
  { value: 'YFI', label: 'YFI - yearn.finance' },
  { value: 'RSR', label: 'RSR - Reserve Rights' },
  { value: 'CEL', label: 'CEL - Celsius' },
  { value: 'SC', label: 'SC - Siacoin' },
  { value: 'ICX', label: 'ICX - ICON' },
  { value: 'ZRX', label: 'ZRX - 0x' },
  { value: 'FTM', label: 'FTM - Fantom' },
  { value: 'REN', label: 'REN - Ren' },
  { value: 'VGX', label: 'VGX - Voyager Token' },
  { value: 'WAVES', label: 'WAVES - Waves' },
  { value: 'REV', label: 'REV - Revain' },
  { value: 'DGB', label: 'DGB - DigiByte' },
  { value: 'ONT', label: 'ONT - Ontology' },
  { value: 'FLOW', label: 'FLOW - Flow' },
  { value: 'IOST', label: 'IOST - IOST' },
  { value: 'OKB', label: 'OKB - OKB' },
  { value: 'PAX', label: 'PAX - Paxos Standard' },
  { value: 'OMG', label: 'OMG - OMG Network' },
  { value: 'RENBTC', label: 'RENBTC - renBTC' },
  { value: 'CELO', label: 'CELO - Celo' },
  { value: 'HNT', label: 'HNT - Helium' },
  { value: '1INCH', label: '1INCH - 1inch' },
  { value: 'AR', label: 'AR - Arweave' },
  { value: 'LRC', label: 'LRC - Loopring' },
  { value: 'MVL', label: 'MVL - MVL' },
  { value: 'NANO', label: 'NANO - Nano' },
  { value: 'CRV', label: 'CRV - Curve DAO Token' },
  { value: 'VTHO', label: 'VTHO - VeThor Token' }
]

module.exports = currencies
